name: HorseLoyalty
version: '${version}'
main: org.horse_loyalty.HorseLoyaltyPlugin
api-version: '1.21'
author: SeuNome
description: Sistema de lealdade para cavalos.
commands:
  lealdadecavalo:
    description: Gerencia a lealdade de um cavalo
    usage: /lealdadecavalo <get|set|item|rename|help|config>
  horsecatalog:
    description: Obtém o catálogo de cavalos
    usage: /horsecatalog
    permission: lealdadecavalo.catalog
  callhorse:
    description: Chama um cavalo específico (nível 8+)
    usage: /callhorse <UUID>
    permission: lealdadecavalo.call
  favoritehorse:
    description: Favorita um cavalo (nível 10)
    usage: /favoritehorse <UUID>
    permission: lealdadecavalo.favorite
  vemcapocoto:
    description: Chama o cavalo favorito
    usage: /vemcapocoto
    permission: lealdadecavalo.favorite
permissions:
  lealdadecavalo.use:
    description: Permite usar comandos básicos do HorseLoyalty
    default: true
  lealdadecavalo.admin:
    description: Permissão administrativa (set, config)
    default: op
  lealdadecavalo.catalog:
    description: Permite usar o catálogo de cavalos
    default: true
  lealdadecavalo.call:
    description: Permite chamar cavalos
    default: true
  lealdadecavalo.favorite:
    description: Permite favoritar e chamar o favorito
    default: true
